---
- name: Required variables
  assert:
    that:
      - rcon is defined
      - rcon_port is defined
      - jvm_ram is defined
      - webhook_id is defined
      - webhook_secret is defined

- name: Create the Minecraft Server User
  user:
    comment: Minecraft Service User
    name: "{{ service_username }}"
    create_home: yes
    home: "{{ home_directory }}"
  become: yes

- name: Install Java
  package:
    name: java-17-openjdk
    state: present
  become: yes

- name: Git Checkout LanBros Minecraft Directory
  git:
    repo: 'https://github.com/zeNkan/lanbros-minecraft.git'
    dest: "{{ repo_directory }}"
  become: yes
  become_user: "{{ service_username }}"
