---
- name: Download Minecraft Server Jar
  get_url:
    url: https://launcher.mojang.com/v1/objects/e00c4052dac1d59a1188b2aa9d5a87113aaf1122/server.jar
    dest: "{{ server_directory }}/server.jar"
    mode: '0711'
  become: yes
  become_user: "{{ service_username }}"

- name: Install server.properties File
  template:
    src: server.properties.j2
    dest: "{{ server_directory }}/server.properties"
    owner: "{{ service_username }}"
    group: "{{ service_group }}"
    mode: 0644
  become: yes
  become_user: "{{ service_username }}"
