---
- name: Install golang
  package:
    name: golang
    state: present
  become: yes

- name: Build Webhook
  shell: 
    chdir: "{{ webhook_directory }}"
    cmd: "go build -o webhook ."
  become: yes
  become_user: minecraft

- name: Install Systemd Unit File
  template:
    src: "webhook.service.j2"
    dest: "/etc/systemd/system/webhook.service"
    owner: root
    group: root
    mode: 0644
  become: yes

- name: Enable and Start the Service
  ansible.builtin.systemd:
    name: "webhook.service"
    state: started
    enabled: yes
  become: yes

- name: Install Firewall Service File
  template:
    src: webhook-firewall-config.xml.j2
    dest: "/etc/firewalld/services/webhook.xml"
    owner: root
    group: root
    mode: 0644
  become: yes

- name: Reload Firewall
  systemd:
    name: firewalld
    state: reloaded
  become: yes

# The service is being referred to the name of the xml file
# with out the .xml ending
- name: Enable Service in Firewall
  firewalld:
    service: "webhook"
    permanent: yes
    state: enabled
  become: yes


