---
- name: Install golang
  package:
    name: golang
    state: present
  become: yes

- name: Build Webhook
  shell: 
    chdir: "{{ webhook_directory }}"
    cmd: "go build -o webhook ."

- name: Install Systemd Unit File
  template:
    src: "webhook.service.j2"
    dest: "/etc/systemd/system/{{ item[:-3] }}"
    owner: root
    group: root
    mode: 0644
  become: yes

- name: Enable and Start the Service
  ansible.builtin.systemd:
    name: "webhook.service.j2"
    state: started
    enabled: yes
  become: yes

